# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none #Change to master for ci

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

# SCA scan with Snyk
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'Snyk-SCA-connection'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: false

# Install node dependencies and build front-end(optional)
- script: |
    echo running server install
    npm install
    echo running client install
    npm run client-install
    echo Running client build
    # npm run client-build
  displayName: 'npm install all and build'

# Zip, archive and publish the build artifact 
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

# Publish build artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'



# SAST analysis with coverity



# Deploy the webapp using the zip file from the archive step
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'kalle-sp2'
    appType: 'webAppLinux'
    appName: 'kalle-test-env'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    startUpCommand: 'npm run start'

# Install docker cli
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

# Run owasp zap container on url 
# fullscan: docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t https://kalle-test-env.azurewebsites.net/ -g gen.conf -x OWASP-ZAP-Report.xml -r scan-report.html
# API version: docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-api-scan.py -t https://kalle-test-env.azurewebsites.net/ -f openapi -g api-scan.conf -x OWASP-ZAP-Report.xml -r api-scan-report.html
- script: |
    echo set chmod
    chmod -R 777  ./
    echo run docker image
    docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t https://kalle-test-env.azurewebsites.net/ -j -g gen.conf -x OWASP-ZAP-Report.xml -r scan-report.html
    echo cat report
    cat scan-report.html
  displayName: 'OWASP zap'
